name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: echo "Hello World!"

  now it is:
    runs-on: ubuntu-20.04
    steps:
      - name: echo date
        run: echo $date

  directory content:
    runs-on: ubuntu-20.04
    steps:
      - name: ls -al
        run: ls -al
